gText_Birch_Welcome::
	.string "Welcome to the Pokémon Escape Room:\n"
	.string "Escape from Shuckle Island!\p"
	.string "$"

gText_Birch_Pokemon::
	.string "This island's Shuckle have caught the\n"
	.string "attention of a certain organization.\p"
	.string "What could these Shuckle be hiding?\p"
	.string "\n"
	.string "$"

gText_Birch_MainSpeech::
	.string "Uncover the Shuckle's secrets as you\n"
	.string "progress through the escape room!\p"
	.string "Solve tricky battles using Gen IV\n"
	.string "mechanics, complete overworld puzzles,\l"
	.string "and test your Pokémon knowledge!\p"
	.string "Get stumped during your adventure?\n"
	.string "No worries!\p"
	.string "Most puzzles offer multiple hints.\n"
	.string "And harder puzzles give better hints.\p"
	.string "If you use all the hints and are still\n"
	.string "stuck, you can even view a solution!\p"
	.string "$"

gText_Birch_AndYouAre::
	.string "Now before we begin, let's find out a bit\n"
	.string "more about you.\p"
	.string "$"

gText_Birch_BoyOrGirl::
	.string "Are you a boy?\n"
	.string "Or are you a girl?$"

gText_Birch_WhatsYourName::
	.string "All right.\n"
	.string "What's your name?$"

gText_Birch_SoItsPlayer::
	.string "So it's {PLAYER}{KUN}?$"

gText_Birch_YourePlayer::
	.string "Ah, okay!\p"
	.string "$"

gText_Birch_AreYouReady::
	.string "Your challenge is about to begin!\p"
	.string "Good luck! And remember: help is always\n"
	.string "available if you need it.\p"
	.string "$"
